# Generated by Django 5.0.3 on 2024-05-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='pay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='pay_payment_status',
            new_name='razorpay_payment_status',
        ),
    ]
