# Generated by Django 5.0.3 on 2024-06-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_customer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
    ]
